package algorithm;

import java.awt.Color;

public class RegisterView extends javax.swing.JDialog {

    public RegisterView(java.awt.Frame parent, AlgorithmApp app, boolean modal) {
        super(parent, modal);
        initComponents();
        MainApp = app;
        valid = false;
        checkid = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox();
        Password = new javax.swing.JPasswordField();
        CPassword = new javax.swing.JPasswordField();
        ID = new javax.swing.JTextField();
        UserName = new javax.swing.JTextField();
        CheckUserName = new javax.swing.JTextField();
        CheckPassword = new javax.swing.JTextField();
        CheckID = new javax.swing.JTextField();
        VaildButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 250));
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(algorithm.AlgorithmApp.class).getContext().getResourceMap(RegisterView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Instructor", "Student" }));
        Type.setName("Type"); // NOI18N

        Password.setText(resourceMap.getString("Password.text")); // NOI18N
        Password.setName("Password"); // NOI18N

        CPassword.setText(resourceMap.getString("CPassword.text")); // NOI18N
        CPassword.setName("CPassword"); // NOI18N
        CPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CPasswordFocusLost(evt);
            }
        });

        ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ID.setName("ID"); // NOI18N

        UserName.setText(resourceMap.getString("UserName.text")); // NOI18N
        UserName.setName("UserName"); // NOI18N

        CheckUserName.setEditable(false);
        CheckUserName.setBorder(null);
        CheckUserName.setName("CheckUserName"); // NOI18N

        CheckPassword.setEditable(false);
        CheckPassword.setBorder(null);
        CheckPassword.setName("CheckPassword"); // NOI18N

        CheckID.setEditable(false);
        CheckID.setBorder(null);
        CheckID.setName("CheckID"); // NOI18N

        VaildButton.setText(resourceMap.getString("VaildButton.text")); // NOI18N
        VaildButton.setName("VaildButton"); // NOI18N
        VaildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaildButtonActionPerformed(evt);
            }
        });

        CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
        CancelButton.setName("CancelButton"); // NOI18N
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SignUpButton.setText(resourceMap.getString("SignUpButton.text")); // NOI18N
        SignUpButton.setName("SignUpButton"); // NOI18N
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(Type, 0, 111, Short.MAX_VALUE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VaildButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SignUpButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VaildButton)
                    .addComponent(CheckUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CheckID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SignUpButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ID.getAccessibleContext().setAccessibleName(resourceMap.getString("ID.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="GUI Managers">
    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        if(CheckValidation() && CheckPassword() && CheckID())
        {
            //add to DB
            MainApp.add(UserName.getText(),Password.getText(),Type.getSelectedIndex(),Integer.parseInt(ID.getText()));
            //Hide Dialog
            MainApp.ExitRegisteration();
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        //Hide Dialog
        MainApp.ExitRegisteration();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void VaildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaildButtonActionPerformed
        CheckValidation();
    }//GEN-LAST:event_VaildButtonActionPerformed

    private void CPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CPasswordFocusLost
        CheckPassword();
    }//GEN-LAST:event_CPasswordFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPassword;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CheckID;
    private javax.swing.JTextField CheckPassword;
    private javax.swing.JTextField CheckUserName;
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JComboBox Type;
    private javax.swing.JTextField UserName;
    private javax.swing.JButton VaildButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    // <editor-fold defaultstate="collapsed" desc="Variables used in the Class">
    private AlgorithmApp MainApp;
    private boolean valid;
    private boolean checkid;// </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Registeration Manager Method">
    //Check Confirmation
    private boolean CheckPassword(){
        //Check Password Confirmation
        if(CPassword.getText().equals(Password.getText()))
        {
            CheckPassword.setForeground(Color.green);
            CheckPassword.setText("Match");
            return true;
        }
        else
        {
            CheckPassword.setForeground(Color.red);
            CheckPassword.setText("Not Match");
            return false;
        }
    }

    //Check Validation
    private boolean CheckValidation(){
        //Check UserName Validation
        valid = MainApp.CheckValidation(UserName.getText());
        if(valid)
        {
            CheckUserName.setForeground(Color.green);
            CheckUserName.setText("Vaild");
        }
        else
        {
            CheckUserName.setForeground(Color.red);
            CheckUserName.setText("Not Valid");
        }
        return valid;
    }

    //Check ID
    private boolean CheckID(){
        checkid = MainApp.CheckID(Type.getSelectedIndex(),Integer.parseInt(ID.getText()));
        if(checkid)
        {
            CheckID.setForeground(Color.green);
            CheckID.setText("Found");
        }
        else
        {
            CheckID.setForeground(Color.red);
            CheckID.setText("Not Found");
        }
        return checkid;
    }// </editor-fold>
}
