package Computation;

import javax.swing.JTable;

public class TimeTable extends javax.swing.JDialog {

    /** Creates new form TimeTable */
    public TimeTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        TimeTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane.setName("jScrollPane"); // NOI18N

        TimeTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sunday", null, null, null, null, null, null, null, null, null},
                {"Monday", null, null, null, null, null, null, null, null, null},
                {"Tuesday", null, null, null, null, null, null, null, null, null},
                {"Wednesady", null, null, null, null, null, null, null, null, null},
                {"Thurasday", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Days", "08:30 to 09:30", "09:45 to 10:45", "11:00 to 12:00", "Break", "13:00 to 14:00", "14:15 to 15:15", "15:30 to 16:30", "16:45 to 17:45", "18:00 to 19:00"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TimeTable2.setName("TimeTable2"); // NOI18N
        TimeTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(TimeTable2);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(algorithm.AlgorithmApp.class).getContext().getResourceMap(TimeTable.class);
        TimeTable2.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title0")); // NOI18N
        TimeTable2.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title1")); // NOI18N
        TimeTable2.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title2")); // NOI18N
        TimeTable2.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title3")); // NOI18N
        TimeTable2.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title4")); // NOI18N
        TimeTable2.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title5")); // NOI18N
        TimeTable2.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title6")); // NOI18N
        TimeTable2.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title7")); // NOI18N
        TimeTable2.getColumnModel().getColumn(8).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title8")); // NOI18N
        TimeTable2.getColumnModel().getColumn(9).setHeaderValue(resourceMap.getString("TimeTable2.columnModel.title9")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TimeTable2;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables

    public JTable GetTable() {
        return TimeTable2;
    }

}
