/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourseEntry.java
 *
 * Created on Nov 12, 2011, 8:09:49 PM
 */

package Admin;

/**
 *
 * @author Ayman
 */
public class CourseEntry extends javax.swing.JDialog {

    /** Creates new form CourseEntry */
    public CourseEntry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Lhours = new javax.swing.JTextField();
        Thours = new javax.swing.JTextField();
        Shours = new javax.swing.JTextField();
        Semster = new javax.swing.JComboBox();
        Instructor = new javax.swing.JComboBox();
        Code = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Credit = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        NewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(algorithm.AlgorithmApp.class).getContext().getResourceMap(CourseEntry.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        Lhours.setText(resourceMap.getString("Lhours.text")); // NOI18N
        Lhours.setEnabled(false);
        Lhours.setName("Lhours"); // NOI18N

        Thours.setText(resourceMap.getString("Thours.text")); // NOI18N
        Thours.setEnabled(false);
        Thours.setName("Thours"); // NOI18N

        Shours.setText(resourceMap.getString("Shours.text")); // NOI18N
        Shours.setEnabled(false);
        Shours.setName("Shours"); // NOI18N

        Semster.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        Semster.setEnabled(false);
        Semster.setName("Semster"); // NOI18N

        Instructor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Instructor.setEnabled(false);
        Instructor.setName("Instructor"); // NOI18N

        Code.setText(resourceMap.getString("Code.text")); // NOI18N
        Code.setEnabled(false);
        Code.setName("Code"); // NOI18N

        Name.setText(resourceMap.getString("Name.text")); // NOI18N
        Name.setEnabled(false);
        Name.setName("Name"); // NOI18N

        Credit.setText(resourceMap.getString("Credit.text")); // NOI18N
        Credit.setEnabled(false);
        Credit.setName("Credit"); // NOI18N

        SaveButton.setText(resourceMap.getString("SaveButton.text")); // NOI18N
        SaveButton.setEnabled(false);
        SaveButton.setName("SaveButton"); // NOI18N

        DeleteButton.setText(resourceMap.getString("DeleteButton.text")); // NOI18N
        DeleteButton.setEnabled(false);
        DeleteButton.setName("DeleteButton"); // NOI18N

        RefreshButton.setText(resourceMap.getString("RefreshButton.text")); // NOI18N
        RefreshButton.setName("RefreshButton"); // NOI18N

        BackButton.setText(resourceMap.getString("BackButton.text")); // NOI18N
        BackButton.setName("BackButton"); // NOI18N

        CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
        CancelButton.setEnabled(false);
        CancelButton.setName("CancelButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Semester", "Credit", "Lecturer", "Thours", "Shours", "Lhours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CourseTable.setName("CourseTable"); // NOI18N
        CourseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CourseTable);
        CourseTable.getColumnModel().getColumn(0).setMinWidth(40);
        CourseTable.getColumnModel().getColumn(0).setMaxWidth(40);
        CourseTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title0")); // NOI18N
        CourseTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title1")); // NOI18N
        CourseTable.getColumnModel().getColumn(2).setMinWidth(55);
        CourseTable.getColumnModel().getColumn(2).setMaxWidth(55);
        CourseTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title4")); // NOI18N
        CourseTable.getColumnModel().getColumn(3).setMinWidth(40);
        CourseTable.getColumnModel().getColumn(3).setMaxWidth(40);
        CourseTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title5")); // NOI18N
        CourseTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title6")); // NOI18N
        CourseTable.getColumnModel().getColumn(5).setMinWidth(45);
        CourseTable.getColumnModel().getColumn(5).setMaxWidth(45);
        CourseTable.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title2")); // NOI18N
        CourseTable.getColumnModel().getColumn(6).setMinWidth(45);
        CourseTable.getColumnModel().getColumn(6).setMaxWidth(45);
        CourseTable.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title3")); // NOI18N
        CourseTable.getColumnModel().getColumn(7).setMinWidth(45);
        CourseTable.getColumnModel().getColumn(7).setMaxWidth(45);
        CourseTable.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("CourseTable.columnModel.title7")); // NOI18N

        NewButton.setText(resourceMap.getString("NewButton.text")); // NOI18N
        NewButton.setName("NewButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Code, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(Semster, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Instructor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Thours)
                            .addComponent(Lhours))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Credit)
                            .addComponent(Name)
                            .addComponent(Shours, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RefreshButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Semster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Thours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Shours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lhours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewButton)
                    .addComponent(SaveButton)
                    .addComponent(DeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshButton)
                    .addComponent(CancelButton)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CourseEntry dialog = new CourseEntry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField Code;
    private javax.swing.JTable CourseTable;
    private javax.swing.JTextField Credit;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JComboBox Instructor;
    private javax.swing.JTextField Lhours;
    private javax.swing.JTextField Name;
    private javax.swing.JButton NewButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox Semster;
    private javax.swing.JTextField Shours;
    private javax.swing.JTextField Thours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
